Add tmate debugging and cleanup step, turn off .flatpak-builder cache
Signed-off-by: Matthew J. Milner <matterhorn103@proton.me>

diff --git a/.github/workflows/flatpak.yml b/.github/workflows/flatpak.yml
--- a/.github/workflows/flatpak.yml
+++ b/.github/workflows/flatpak.yml
@@ -65,6 +65,10 @@ jobs:
         repository: flathub/shared-modules
         path: shared-modules
 
+    - name: Setup tmate session
+      if: failure()
+      uses: mxschmitt/action-tmate@v3
+
     - name: Move manifest
       run: mv src/avogadroapp/flatpak/org.openchemistry.Avogadro2.yaml ./
 
@@ -74,4 +78,14 @@ jobs:
         bundle: avogadro2.flatpak
         branch: nightly
         manifest-path: org.openchemistry.Avogadro2.yaml
+        cache: false
         cache-key: flatpak-builder-${{ github.sha }}
+    
+    - name: Cleanup
+      if: ${{ always() }} # To ensure this step runs even when earlier steps fail
+      shell: bash
+      run: |
+        ls -la ./
+        rm -rf ./* || true
+        rm -rf ./.??* || true
+        ls -la ./
